### ISSUE TITLE
Only one assignment in cache?

### ISSUE THREAD

**Issue by wolfj95** [cproctor/repoview#1]
https://github.com/cproctor/repoview/blob/e3bd0a292d6b5f5ec9560cd67bc35747d22415d5/tasks/helpers.py#L43

It seems that you can only get the status for one set of assignments at a time. 

For example, when I try to get the repo status of the bank lab assignment, I think this is using the cache from the data science project and throwing an error when there are no projects with the bank lab name in the cache.

**Comment by wolfj95** [comment]
Seems like it can be fixed by adding `if project_base_repo.name in cache:` before these lines

https://github.com/cproctor/repoview/blob/e3bd0a292d6b5f5ec9560cd67bc35747d22415d5/tasks/helpers.py#L46-L47

**Comment by cproctor** [comment]
Haha that was careless. Your proposed solution looks good to me.
